name: "execute test programs"
on:
  pull_request:
    paths:
      - 'src/**/*.nim'
      - 'tests/**/*.nim'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.0.0'
      - name: install dependencies
        run: nimble install https://github.com/Azumabashi/nim-propositional-logic/
        # install with url because as of 2023/08/09 this library is not included to nimble.directory.
      - name: execute test programs
        run: nim c -r tests/testRevision3