name: "execute test programs"
on:
  pull_request:
    paths:
      - 'src/**/*.nim'
      - 'tests/**/*.nim'
      - '.github/workflows/run-test.yml'

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version: ["1.6.16", "2.0.0"]
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{matrix.nim-version}}
      - name: install dependencies
        run: nimble install propositionalLogic
      - name: execute test programs
        run: nimble test